# Experiment 2 - Numerical Python (NUMPY)

**NORMALIZATION PROBLEM**: Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
expressed as: 

$$
Z = \frac{X - \mu}{\sigma}
$$

In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
.std() calls. 

In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as *X_normalized.npy*

In [64]:
import numpy as np

X = np.random.random((5,5))          # creates a 5x5 array with random values
M = np.mean(X)                       # computes the mean of array X
SD = np.std(X)                       # computes the standard deviation of array X
Z = (X-M) / SD                       # performs the normalization equation
np.save("X_normalized.npy",Z)        # saves array Z as "X_normalized.npy"
data = np.load("X_normalized.npy")   # loads the array from file "X_normalized.npy"

print(X)
print ("")
print (data)

[[0.15876216 0.09505427 0.02329905 0.07021459 0.9851757 ]
 [0.54567002 0.35925278 0.31503234 0.9796749  0.8683845 ]
 [0.32408004 0.13029327 0.76157271 0.03299959 0.07205149]
 [0.80377121 0.43078823 0.20760617 0.38777069 0.35175575]
 [0.5645121  0.34542222 0.94183019 0.25156594 0.13635565]]

[[-0.79719142 -1.00284694 -1.23448005 -1.08303192  1.87055514]
 [ 0.45178631 -0.14998741 -0.29273546  1.85279799  1.49354134]
 [-0.26352857 -0.88909188  1.14874205 -1.20316572 -1.07710223]
 [ 1.28496307  0.08093626 -0.63951802 -0.05792869 -0.17418856]
 [ 0.51261046 -0.19463386  1.73063144 -0.49761142 -0.86952191]]


**DIVISIBLE BY 3 PROBLEM**: Create the following 10 x 10 ndarray.

$$
A = 
\begin{bmatrix}
1 & 4 & \cdots & 81 & 100 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
8281 & 8464 & \cdots & 9801 & 10000
\end{bmatrix}
$$

which are the squares of the first 100 positive integers.

From this ndarray, determine all the elements that are divisible by 3. Save the result as *div_by_3.npy*

In [65]:
import numpy as np

arr = np.arange(1,101,1)                     # creates an array with values from 1 to 100
arr_squared = arr ** 2                       # squares each element of the array
arr_squared = arr_squared.reshape(10,10)     # reshapes the array into 10x10 2D array
 
div = arr_squared[arr_squared % 3 == 0]      # selects elements divisible by 3
np.save("div_by_3.npy", div)                 # saves array div as "div_by_3.npy"
div_final = np.load("div_by_3.npy")          # loads the array from file "div_by_3.npy"

print(arr_squared)
print("")
print(div_final)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
